openapi: 3.0.3
info:
  title: Featured Offers Management API
  description: Admin API for creating, updating, and managing featured offers displayed on the landing page carousel
  version: 1.0.0
  contact:
    name: Jomla Development Team

servers:
  - url: https://us-central1-{project-id}.cloudfunctions.net
    description: Firebase Cloud Functions

paths:
  /featuredOffers:
    get:
      summary: List all featured offers
      description: |
        Retrieve all featured offers. Admins see all statuses; regular users see only active offers.
      operationId: listFeaturedOffers
      tags:
        - Featured Offers
      security:
        - firebaseAuth: []
      parameters:
        - name: status
          in: query
          description: Filter by status (admin only)
          schema:
            type: string
            enum: [draft, active, inactive, all]
            default: active
        - name: limit
          in: query
          description: Maximum number of offers to return
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: orderBy
          in: query
          description: Sort order
          schema:
            type: string
            enum: [displayOrder, createdAt, publishedAt]
            default: displayOrder
      responses:
        '200':
          description: List of featured offers
          content:
            application/json:
              schema:
                type: object
                properties:
                  offers:
                    type: array
                    items:
                      $ref: '#/components/schemas/FeaturedOffer'
                  total:
                    type: integer
                    description: Total count of offers matching filter
                    example: 15
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Create a new featured offer
      description: |
        Admin-only endpoint to create a new featured offer.
        Media file must be uploaded to Firebase Storage first, then URL provided here.
      operationId: createFeaturedOffer
      tags:
        - Featured Offers
      security:
        - firebaseAuth: []
        - adminToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFeaturedOfferRequest'
      responses:
        '201':
          description: Featured offer created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  offerId:
                    type: string
                    example: "featured_abc123"
                  offer:
                    $ref: '#/components/schemas/FeaturedOffer'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Unauthorized - admin access required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /featuredOffers/{offerId}:
    get:
      summary: Get a specific featured offer
      description: Retrieve details of a single featured offer by ID
      operationId: getFeaturedOffer
      tags:
        - Featured Offers
      security:
        - firebaseAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          description: Featured offer ID
          schema:
            type: string
      responses:
        '200':
          description: Featured offer details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeaturedOffer'
        '404':
          description: Offer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update a featured offer
      description: Admin-only endpoint to update an existing featured offer
      operationId: updateFeaturedOffer
      tags:
        - Featured Offers
      security:
        - firebaseAuth: []
        - adminToken: []
      parameters:
        - name: offerId
          in: path
          required: true
          description: Featured offer ID to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateFeaturedOfferRequest'
      responses:
        '200':
          description: Featured offer updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  offerId:
                    type: string
                    example: "featured_abc123"
                  offer:
                    $ref: '#/components/schemas/FeaturedOffer'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Offer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a featured offer
      description: |
        Admin-only endpoint to delete a featured offer.
        Associated media files in Firebase Storage are also deleted.
      operationId: deleteFeaturedOffer
      tags:
        - Featured Offers
      security:
        - firebaseAuth: []
        - adminToken: []
      parameters:
        - name: offerId
          in: path
          required: true
          description: Featured offer ID to delete
          schema:
            type: string
      responses:
        '200':
          description: Featured offer deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  offerId:
                    type: string
                    example: "featured_abc123"
                  message:
                    type: string
                    example: "Featured offer and associated media deleted"
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Offer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /featuredOffers/{offerId}/publish:
    post:
      summary: Publish a featured offer
      description: |
        Change offer status from 'draft' to 'active' and trigger push notification to all users.
        Sets publishedAt timestamp.
      operationId: publishFeaturedOffer
      tags:
        - Featured Offers
      security:
        - firebaseAuth: []
        - adminToken: []
      parameters:
        - name: offerId
          in: path
          required: true
          description: Featured offer ID to publish
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sendNotification:
                  type: boolean
                  description: Whether to send push notification to users
                  default: true
      responses:
        '200':
          description: Featured offer published successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  offerId:
                    type: string
                    example: "featured_abc123"
                  publishedAt:
                    type: string
                    format: date-time
                    example: "2025-11-05T10:30:00Z"
                  notificationSent:
                    type: boolean
                    example: true
        '400':
          description: Invalid request (offer already published)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /featuredOffers/{offerId}/analytics:
    get:
      summary: Get analytics for a featured offer
      description: Retrieve view count, conversion rate, and engagement metrics
      operationId: getFeaturedOfferAnalytics
      tags:
        - Featured Offers
        - Analytics
      security:
        - firebaseAuth: []
        - adminToken: []
      parameters:
        - name: offerId
          in: path
          required: true
          description: Featured offer ID
          schema:
            type: string
      responses:
        '200':
          description: Analytics data
          content:
            application/json:
              schema:
                type: object
                properties:
                  offerId:
                    type: string
                    example: "featured_abc123"
                  viewCount:
                    type: integer
                    description: Total number of views
                    example: 1523
                  addToCartCount:
                    type: integer
                    description: Number of times "Add to Cart" was clicked
                    example: 218
                  conversionRate:
                    type: number
                    description: Conversion rate (addToCartCount / viewCount)
                    example: 0.143
                  averageViewDuration:
                    type: number
                    description: Average time spent viewing (seconds)
                    example: 8.5
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    FeaturedOffer:
      type: object
      required:
        - id
        - title
        - mediaType
        - mediaUrl
        - displayOrder
        - ctaText
        - status
      properties:
        id:
          type: string
          example: "featured_abc123"
        title:
          type: string
          example: "Weekend Special Bundle"
        description:
          type: string
          example: "Save 40% on fresh produce this weekend"
        mediaType:
          type: string
          enum: [image, video]
          example: "video"
        mediaUrl:
          type: string
          format: uri
          example: "https://storage.googleapis.com/bucket/featured-offers/abc123/media.mp4"
        thumbnailUrl:
          type: string
          format: uri
          example: "https://storage.googleapis.com/bucket/featured-offers/abc123/thumbnail.jpg"
        videoDuration:
          type: number
          description: Duration in seconds (for videos only)
          example: 15
        linkedOfferId:
          type: string
          description: Reference to existing offer in offers collection
          example: "offer_xyz789"
        linkedProductIds:
          type: array
          description: Direct links to products (alternative to linkedOfferId)
          items:
            type: string
          example: ["prod_123", "prod_456"]
        displayOrder:
          type: integer
          description: Sort order in carousel (1, 2, 3...)
          example: 1
        backgroundColor:
          type: string
          description: Hex color code for loading state
          example: "#FF6B35"
        ctaText:
          type: string
          description: Call-to-action button text
          example: "Add to Cart"
        ctaAction:
          type: string
          enum: [add_to_cart, view_details, external_link]
          example: "add_to_cart"
        status:
          type: string
          enum: [draft, active, inactive]
          example: "active"
        publishedAt:
          type: string
          format: date-time
          example: "2025-11-05T10:30:00Z"
        expiresAt:
          type: string
          format: date-time
          example: "2025-11-08T23:59:59Z"
        viewCount:
          type: integer
          example: 1523
        addToCartCount:
          type: integer
          example: 218
        createdAt:
          type: string
          format: date-time
          example: "2025-11-04T15:20:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-11-05T10:30:00Z"
        createdBy:
          type: string
          description: Admin user ID who created the offer
          example: "admin_user_123"

    CreateFeaturedOfferRequest:
      type: object
      required:
        - title
        - mediaType
        - mediaUrl
        - displayOrder
        - ctaText
        - ctaAction
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 500
        mediaType:
          type: string
          enum: [image, video]
        mediaUrl:
          type: string
          format: uri
          description: Firebase Storage URL (media must be uploaded first)
        thumbnailUrl:
          type: string
          format: uri
        videoDuration:
          type: number
          description: Required if mediaType is 'video'
        linkedOfferId:
          type: string
        linkedProductIds:
          type: array
          items:
            type: string
        displayOrder:
          type: integer
          minimum: 1
        backgroundColor:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
        ctaText:
          type: string
          minLength: 1
          maxLength: 50
        ctaAction:
          type: string
          enum: [add_to_cart, view_details, external_link]
        status:
          type: string
          enum: [draft, active, inactive]
          default: draft
        expiresAt:
          type: string
          format: date-time

    UpdateFeaturedOfferRequest:
      type: object
      description: All fields optional - only provided fields will be updated
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 500
        mediaUrl:
          type: string
          format: uri
        thumbnailUrl:
          type: string
          format: uri
        videoDuration:
          type: number
        linkedOfferId:
          type: string
        linkedProductIds:
          type: array
          items:
            type: string
        displayOrder:
          type: integer
          minimum: 1
        backgroundColor:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
        ctaText:
          type: string
          minLength: 1
          maxLength: 50
        ctaAction:
          type: string
          enum: [add_to_cart, view_details, external_link]
        status:
          type: string
          enum: [draft, active, inactive]
        expiresAt:
          type: string
          format: date-time

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          example: "invalid-argument"
        message:
          type: string
          example: "Invalid request parameters"
        details:
          type: object
          additionalProperties: true

  securitySchemes:
    firebaseAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Firebase Authentication ID token
    adminToken:
      type: apiKey
      in: header
      name: X-Admin-Token
      description: Admin custom claim required (auth.token.admin == true)
